apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifacts-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: <nfs-server-path>
    server: <nfs-server>