---
- debug:
    var: cur_status

- name: find needed ci statuses
  block:
    - name: update status if it doesn't match to task status
      when: "cur_status['state'] != states[run_task['result']]"
      gh_commit:
        sha:  "{{ commit }}"
        organization: "{{ github.organization }}"
        token: "{{ github.token }}"
        repo: "{{ github.repo }}"
        command: set_status
        status: {"state":"{{ states[run_task['result']] }}",
                 "description": "{{ states[run_task['result']] }} #{{ run_id }}",
                 "context": "{{ ci_stream }}"}
      register: commit_data

    - set_fact:
        statuses_updated: true
  when: 'ci_stream|string == cur_status["context"]'
