---
# this playbook does initial container setup
- hosts: localhost
  any_errors_fatal: true
  strategy: debug
  vars_files:
    - vars/variables.yml

  tasks:
    - name: configure git
      git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
      with_items:
        - { name: 'user.email', value: 'me@dockerbot' }
        - { name: 'user.name', value: 'DockerBot' }
        - { name: 'fetch.prune', value: 'true'}

    - include: plays/update_plays.yml

    - name: run full env setup
      command: "python -m cfme.scripting.quickstart"
      args:
        chdir: "{{  cfme_repo_dir }}"
      environment:
        PIP_TRUSTED_HOST: "{{ wheel.host }}"
        PIP_FIND_LINKS: "{{ wheel.url }}"

    - name: enable ansible logging
      template:
        src: "templates/ansible.cfg"
        dest: "/root/.ansible.cfg"
